config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root to: 'welcome#index'
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  def self.search(search)
  	if search
    	# Student.where(['name LIKE ?', "%#{search}%"])
    	 Student.where(['name LIKE ? OR subject LIKE ?',"%#{search}%","%#{search}%"])
  	else
    	Student.all
    	# find(:all)
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :students
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },uniqueness: true
  validates :password, length: {minimum: 6},presence: true
  validates :password, confirmation: {case_sensitive: true}
  # validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	helper_method :sort_column, :sort_direction
	before_action :authenticate_user!
	before_action :set_user, only: [:new,:create]
	def index
		@students = Student.all
		@students = Student.order(sort_column + " " + sort_direction)
		if params[:radio_input] == 'name'
			@students = Student.search(params[:search])
		elsif params[:radio_input] == 'subject'

			@students = Student.search(params[:search])
		else
			Student.all
		end
		# if params[:radio_input] == 'name'
		
		# 	@search = params[:search]

		# 	if @search.present?
		# 		@name = @search["name"]
		# 		@students = Student.where("name LIKE ? OR subject LIKE ?", "%#{@name}%","%#{@name}%")
		# 	end
		# elsif params[:radio_input] == 'subject'
		# 	@search = params[:search]
		# 	if @search.present?
		# 		@name = @search["name"]
		# 		@students = Student.where("name LIKE ? OR subject LIKE ?", "%#{@name}%","%#{@name}%")
		# 	end
		# else
		# 	Student.all
		# end		
	end

	def new
		@student = Student.new
	end

	def show
		@student = Student.find(params[:id])
	end

	def edit
		@student = Student.find(params[:id])
	end

	def create
		@student = @user.students.create(student_params)
		if @student.save
			redirect_to students_path
		else
			render 'new'
		end
	end

	def update
		@student = Student.find(params[:id])
		if @student.update(student_params)
			redirect_to students_path
		else
			render 'edit'
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to students_path
	end

	private
	def student_params
		params.require(:student).permit(:name,:subject,:age,:user_id,:search,:in)
	end

	def set_user
		@user = current_user
	end

	def sort_column
		Student.column_names.include?(params[:sort]) ? params[:sort] : "name"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
  		title ||= column.titleize
  		css_class = column == sort_column ? "current #{sort_direction}" : nil
  		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end

	def show_errors(object, field_name)
  		if object.errors.any?
    		if !object.errors.messages[field_name].blank?
      			object.errors.messages[field_name].join(", ")
    		end
  		end
	end 

end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		messages = resource.errors.details.keys.map { |attr|      content_tag(:li, resource.errors.full_messages_for(attr).first) }.join
		# messages = resource.errors.full_messages.map { |map| content_tag(:li, msg)}.join
	end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
 
<!-- Footer -->
<footer class="page-footer font-small blue pt-4">
	<!-- Footer Links -->
  <div class="container-fluid text-center text-md-left" id="footer">
		<!-- Grid row -->
   	<div class="row">
      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">
					<!-- Content -->
        <h5 class="text-uppercase">Devise</h5>
        <!-- <p>Here you can use rows and columns to organize your footer content.</p> -->

      </div>
      <!-- Grid column -->
				<!-- Grid column -->
      <div class="col-md-6 mb-md-0 mb-3">
        <div>
					<% if current_user.present? %>
					<%# byebug %>
						<%= current_user.email %>
					<%end %>
				</div>
      </div>
    </div>
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  
  <!-- Copyright -->

</footer>
<!-- Footer

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm  navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">Devise App</a>
  <img src='/assets/logo1.png', class="logo" %>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <!-- <a class="nav-link" href="#"> -->
        <a href ="#"> <%#= link_to 'posts',posts_path ,class: "nav-link"%></a>
    </li>
    <li class="nav-item">
      <a href="#"><%#= link_to 'create_post',new_post_path, class: "nav-link"%></a>
    </li>

    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" >Menu
        <!-- <img src="img_avatar.png" alt="Avatar"> -->
       <%#if#  current_user.profile.attached? %>
        <%#= image_tag current_user.profile ,class: "img"%>
        <%# end %>

          <%#= image_tag current_user.profile %>
      
      </a>
      <div class="dropdown-menu">
        <% if user_signed_in? %>
          <a href="#"><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "dropdown-item"%></a>
          <a href="#"><%= link_to 'Edit User', edit_user_registration_path, class: "dropdown-item" %></a>
          <a class="dropdown-item" href="#"><%= link_to 'Change password',  new_user_password_path(current_user),method: :get ,class: "dropdown-item"%></a>
        <% else %>
          <a href="#"><%= link_to 'login',  new_user_session_path , class: "dropdown-item"%></a>
          <a href="#"><%= link_to 'signup',   new_user_registration_path , class: "dropdown-item" %></a>
        <% end %>

      </div>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container-fluid" >
      
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= render 'layouts/footer'%>

    </div>
   

    
  </body>
</html>
<!-- style="background-image: url('/assets/log4.jpg');,height: 550px;position:absolute;" -->

app/views/students/_form.html.erb
<% if user_signed_in? %>
	<div class="student-form">
		<%if current_user.present? %>

			<%= form_with( model: [@student],  local: true) do |form |%>
				<p>
					<%#= form.label :name ,class: "label"%><br>
					<%= form.text_field :name, class: "name", placeholder: "name" %>
				</p>
				<p>
					<%#= form.label :age, class: "label" %><br>
					<%= form.select :age,(1..21).to_a.map{ |n| [n,n]}.insert(0,"select age")%>
				</p>
				<p>
					<%#= form.label :subject, class: "label" %><br>
					<%= form.text_field :subject , class: "name",placeholder: "subject"%>
				</p>
				<p>
					<%= form.hidden_field :user_id, value: current_user.id %>
				</p>
				<p>
					<%= form.submit "create student" , class: "student-button" %>
					<button class="student-button"><%= link_to 'back', students_path %></button>
				</p>

			<% end %>
		<% end %>
	</div>
<% end %>

app/views/students/edit.html.erb
<%= render 'form' %>
<%#= link_to 'back', students_path %>

app/views/students/index.html.erb
<div class="student-index">
  <div class="search">
    <!-- with form with -->
    <%#= form_with url: students_path , method: :get do |form| %>
      <%#= form.label(:search, "search ") %>
      <%#= form.text_field(:search) %>
      <%#= form.submit "search", class: "glyphicon glyphicon-search" %>
    <%# end %>
    <!-- with simple form -->
      <%#= simple_form_for :search, url: students_path,method: "GET",html: {class: 'form-inline'} do |f| %>
        <%#= f.input :name,input_html: {value: ""} %>
        <!-- <%#=f.submit "search", class: "btn btn-primary" %><br /> -->
        <!-- <p> -->
        <!-- <%#=radio_button_tag 'radio_input',"name" %>Name -->
        <!-- <%#=radio_button_tag 'radio_input',"subject" %>Subject -->
      <!-- </p> -->
      <!-- <%# end %> -->

      <%= form_tag students_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
           <%= submit_tag "Search", :name => nil %><br>
           <%= radio_button_tag 'radio_input', 'name' %> Name 
           <%= radio_button_tag 'radio_input', 'subject' %> Subject 
        </p>
      <% end %>
  </div>

	<div>
		<%= button_to "new" ,new_student_path, method: :get,class: "index-button" %>
	</div>
  <p class="title">Student Records</p><br>
	<table id="table-index">
    <tr>
			<th class="th-index" ><%#= link_to "name", :sort => "name" %><%= sortable "name"%></th>
			<th class="th-index" ><%#= link_to "name, :sort => "name %>age</th>
			<th class="th-index" ><%#= link_to "subject", :sort => "subject" %><%= sortable "subject" %></th>
			<th class="th-index"></th>
			<th class="th-index"></th>
			<th class="th-index"></th>
		</tr>
    <% @students.each do |student| %>
      <tr>
				<td class="td-index"><%= student.name %></td>
				<td class="td-index"><%= student.age %></td>
				<td class="td-index"><%= student.subject %></td>
				<td><%= button_to "show", student_path(student), method: :get, class: "index-button"%></td>
				<td><%= button_to "edit", edit_student_path(student), method: :get, class: "index-button"%></td>
				<td><%= button_to "destroy", student_path(student), method: :delete, class: "index-button"%></td>
				
			</tr>
    <% end %>
	</table>	
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="student-form">
	<p>
		<stong>Name:</stong>
		<%= @student.name%>
	</p>
	<p>
		<strong>Age</strong>
		<%= @student.age %>
	</p>
	<p>
		<strong>subject</strong>
		<%= @student.subject %>
	</p>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <%#= link_to 'logout', destroy_user_session_path,method: :delete%>
    <div class="index">
    	<h1> welcome</h1>
    	<% if user_signed_in? %>
    		welcome <%= current_user.email %><br />
    	<% end %>
    	<button class="button"><%=link_to 'New Student',new_student_path %></button><br>
    	<button class="button"><%=link_to 'Student',students_path %></button>
    </div>

<% end %>